name: happybara
app_id: da_RxJIdtAUEE4w
owner: welldesignedsystem
package: .
kind: wasmer.io/App.v0
annotations:
  shipitcli.com/config:
    build_command: npm run build
    commands: {}
    convert_redirects: true
    extra_dependencies: []
    node_version: '22'
    package_manager: npm
    port: 8080
    static_dir: out
    static_generator: next
    sws_version: 2.38.0
  shipitcli.com/provider: node-static
  shipitcli.com/version: 0.19.8
